/* Restored management screens backed by the SIMHQ API. */
const originalRender = render;
render = function () { originalRender(); const side=document.querySelector('.side'); if (!side) return; [['teams','♧ Teams'],['users','⚿ Users'],['reports','⇩ Reports']].forEach(([id,label])=>{let n=document.createElement('div');n.className='nav '+(page===id?'active':'');n.textContent=label;n.onclick=()=>go(id);side.append(n)}); if({teams,users,reports}[page]) ({teams,users,reports}[page])(); };
function teams(){app.innerHTML=`<div class="head"><div><h1>Teams</h1><p>Create operational teams and assign agents to them.</p></div>${write()?'<button class="primary" onclick="newTeam()">+ Add team</button>':''}</div><div class="card tablewrap"><table><thead><tr><th>TEAM</th><th>ACTIVE AGENTS</th><th>ACTIVE SIMS</th></tr></thead><tbody>${state.teams.map(t=>`<tr><td><b>${e(t.name)}</b></td><td>${state.agents.filter(a=>a.team===t.name&&a.status==='active').length}</td><td>${state.sims.filter(s=>s.team===t.name&&s.status==='in_use').length}</td></tr>`).join('')||'<tr><td colspan="3">No teams yet.</td></tr>'}</tbody></table></div>`}
function newTeam(){open(`<div class="dhead"><h2>Add team</h2><button onclick="close()">×</button></div><form class="form" onsubmit="saveTeam(event)"><div class="wide"><label>TEAM NAME</label><input name="name" required></div><div class="wide actions"><button type="button" class="secondary" onclick="close()">Cancel</button><button class="primary">Save team</button></div></form>`)}
async function saveTeam(ev){ev.preventDefault();try{await api('/api/teams',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(ev.target)))});close();await load();go('teams')}catch(x){alert(x.message)}}
function agents(){app.innerHTML=`<div class="head"><div><h1>Agents</h1><p>Manage agents, teams, phone assignments, and damage reports.</p></div>${write()?'<button class="primary" onclick="newAgent()">+ Add agent</button>':''}</div><div class="card tablewrap"><table><thead><tr><th>AGENT</th><th>EMPLOYEE ID</th><th>TEAM</th><th>PHONE</th><th>STATUS</th><th></th></tr></thead><tbody>${state.agents.map(a=>`<tr><td><b>${e(a.name)}</b></td><td>${e(a.employeeId)}</td><td>${e(a.team||'Unassigned')}</td><td>${e(a.phone||'—')}</td><td>${e(a.status)}</td><td>${write()?`<button class="secondary" onclick="damageForm('${a.id}','${e(a.name)}')">Damage report</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">No agents yet.</td></tr>'}</tbody></table></div>`}
function newAgent(){open(`<div class="dhead"><h2>Add agent</h2><button onclick="close()">×</button></div><form class="form" onsubmit="saveAgent(event)"><div><label>FULL NAME</label><input name="name" required></div><div><label>EMPLOYEE ID</label><input name="employeeId" required></div><div><label>PHONE</label><input name="phone"></div><div><label>TEAM</label><select name="teamId">${state.teams.map(t=>`<option value="${t.id}">${e(t.name)}</option>`).join('')}</select></div><div><label>STATUS</label><select name="status"><option>active</option><option>suspended</option></select></div><div class="wide"><label>NOTES</label><textarea name="note"></textarea></div><div class="wide actions"><button type="button" class="secondary" onclick="close()">Cancel</button><button class="primary">Save agent</button></div></form>`)}
async function saveAgent(ev){ev.preventDefault();try{await api('/api/agents',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(ev.target)))});close();await load();go('agents')}catch(x){alert(x.message)}}
function assignForm(id){open(`<div class="dhead"><h2>Assign SIM</h2><button onclick="close()">×</button></div><form class="form" onsubmit="saveAssignment(event,'${id}')"><div><label>AGENT</label><select name="agentId">${state.agents.filter(a=>a.status==='active').map(a=>`<option value="${a.id}">${e(a.name)}</option>`).join('')}</select></div><div><label>TEAM</label><select name="teamId">${state.teams.map(t=>`<option value="${t.id}">${e(t.name)}</option>`).join('')}</select></div><div class="wide"><label>REASON / NOTES</label><textarea name="note"></textarea></div><div class="wide actions"><button type="button" class="secondary" onclick="close()">Cancel</button><button class="primary">Assign</button></div></form>`)}
async function saveAssignment(ev,id){ev.preventDefault();try{await api('/api/sims/'+id+'/assign',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(ev.target)))});close();await load();go('sims')}catch(x){alert(x.message)}}
const originalList=list; list=function(){originalList(); if(!write())return;document.querySelectorAll('#rows tr').forEach((row,i)=>{const s=state.sims.filter(x=>[x.number,x.iccid,x.msisdn,x.network,x.agent,x.team].join(' ').toLowerCase().includes((document.querySelector('#q')?.value||'').toLowerCase()))[i];if(!s)return;const cell=row.lastElementChild;cell.insertAdjacentHTML('beforeend',` <button class="secondary" onclick="assignForm('${s.id}')">Assign</button>`);});};
function damageForm(agentId,name){open(`<div class="dhead"><h2>Damage report · ${name}</h2><button onclick="close()">×</button></div><form class="form" onsubmit="saveDamage(event,'${agentId}')"><div><label>ITEM</label><input name="item" required></div><div><label>CONDITION</label><select name="condition"><option>Damaged</option><option>Lost</option><option>Needs repair</option><option>Replaced</option></select></div><div><label>DAMAGE DATE</label><input type="date" name="damagedOn" required></div><div class="wide"><label>NOTES</label><textarea name="notes" required></textarea></div><div class="wide actions"><button type="button" class="secondary" onclick="close()">Cancel</button><button class="primary">Save report</button></div></form>`)}
async function saveDamage(ev,agentId){ev.preventDefault();try{let b=Object.fromEntries(new FormData(ev.target));b.agentId=agentId;await api('/api/damage-reports',{method:'POST',body:JSON.stringify(b)});close();alert('Damage report saved.')}catch(x){alert(x.message)}}
function users(){if(me.role!=='admin'){app.innerHTML='<div class="card">Administrator access is required.</div>';return}app.innerHTML=`<div class="head"><div><h1>Users</h1><p>Create database-backed accounts and roles.</p></div><button class="primary" onclick="newUser()">+ Create user</button></div><div class="card tablewrap"><table><thead><tr><th>NAME</th><th>USERNAME</th><th>ROLE</th><th>STATUS</th></tr></thead><tbody>${(state.users||[]).map(u=>`<tr><td>${e(u.name)}</td><td>${e(u.username)}</td><td>${e(u.role)}</td><td>${u.active?'Active':'Inactive'}</td></tr>`).join('')}</tbody></table></div>`}
function newUser(){open(`<div class="dhead"><h2>Create user</h2><button onclick="close()">×</button></div><form class="form" onsubmit="saveUser(event)"><div><label>FULL NAME</label><input name="name" required></div><div><label>USERNAME</label><input name="username" required></div><div><label>PASSWORD</label><input name="password" type="password" required minlength="8"></div><div><label>ROLE</label><select name="role"><option>admin</option><option>supervisor</option><option>team_leader</option><option>agent</option></select></div><div class="wide actions"><button type="button" class="secondary" onclick="close()">Cancel</button><button class="primary">Create user</button></div></form>`)}async function saveUser(ev){ev.preventDefault();try{await api('/api/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(ev.target)))});close();await load();go('users')}catch(x){alert(x.message)}}
function reports(){app.innerHTML=`<div class="head"><div><h1>Reports</h1><p>Download current SIM inventory.</p></div></div><div class="card"><button class="primary" onclick="downloadCSV()">⇩ Download SIM inventory CSV</button></div>`}function downloadCSV(){const h=['number','msisdn','iccid','network','status','agent','team'];const csv=[h.join(','),...state.sims.map(s=>h.map(k=>'"'+String(s[k]||'').replaceAll('"','""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='sim-inventory.csv';a.click()}
render();
